curl -XDELETE localhost:9200/user

curl -XPOST localhost:9200/user -d '
{"index": 
  { "analysis": {
       "filter": {
                "name_ngrams" : {
                    "type": "edgeNGram", 
                    "min_gram": 1, 
                    "max_gram": 50, 
                    "side":"front"
                }},
       "analyzer": { "partial_search" : {
                        "type":"custom",
                        "tokenizer": "standard",
                        "filter": [
                            "standard",
                            "lowercase",
                            "asciifolding", 
                            "name_ngrams"
                        ]
                    },
                    "full_name": {
                       "type":"custom",
                       "tokenizer":"standard",
                       "filter":[
                          "standard",
                          "lowercase",
                          "asciifolding"
                       ]
                    }
                } 
        }
    }
}'

curl -XPUT localhost:9200/user/expertise/_mapping -d '{
    "properties" : {
        "expertise" : {
            "index_analyzer" : "partial_search",
            "search_analyzer" : "full_name",
            "type" : "string"
        }
    }
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Liam Brown",
    "expertise" : "HTML5",
    "expertiseList" : ["HTML5", "Angular", "Saas", "Nodejs", "Flash"],
    "weight" : 500,
    "idUser" : "liam-brown",
    "photo" : "/images/people/perfil_1.png",
    "phone" : "+506-83097721",
    "email" : "liam.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Liam Brown",
    "expertise" : "Nodejs",
    "expertiseList" : ["HTML5", "Angular", "Saas", "Nodejs", "Flash"],
    "weight" : 400,
    "idUser" : "liam-brown",
    "photo" : "/images/people/perfil_1.png",
    "phone" : "+506-83097721",
    "email" : "liam.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Liam Brown",
    "expertise" : "Saas",
    "expertiseList" : ["HTML5", "Nodejs", "Saas", "Angular", "Flash"],
    "weight" : 300,
    "idUser" : "liam-brown",
    "photo" : "/images/people/perfil_1.png",
    "phone" : "+506-83097721",
    "email" : "liam.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Liam Brown",
    "expertise" : "Angular",
    "expertiseList" : ["HTML5", "Nodejs", "Saas", "Angular", "Flash"],
    "weight" : 200,
    "idUser" : "liam-brown",
    "photo" : "/images/people/perfil_1.png",
    "phone" : "+506-83097721",
    "email" : "liam.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Liam Brown",
    "expertise" : "Flash",
    "expertiseList" : ["HTML5", "Nodejs", "Saas", "Angular", "Flash"],
    "weight" : 100,
    "idUser" : "liam-brown",
    "photo" : "/images/people/perfil_1.png",
    "phone" : "+506-83097721",
    "email" : "liam.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "David James",
    "expertise" : "Saas",
    "expertiseList" : ["Saas", "Angular", "Flash", "HTML5", "Nodejs"],
    "weight" : 500,
    "idUser" : "david-james",
    "photo" : "/images/people/perfil_2.png",
    "phone" : "+506-82221338",
    "email" : "david.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "David James",
    "expertise" : "Angular",
    "expertiseList" : ["Saas", "Angular", "Flash", "HTML5", "Nodejs"],
    "weight" : 400,
    "idUser" : "david-james",
    "photo" : "/images/people/perfil_2.png",
    "phone" : "+506-82221338",
    "email" : "david.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "David James",
    "expertise" : "Flash",
    "expertiseList" : ["Saas", "Angular", "Flash", "HTML5", "Nodejs"],
    "weight" : 300,
    "idUser" : "david-james",
    "photo" : "/images/people/perfil_2.png",
    "phone" : "+506-82221338",
    "email" : "david.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "David James",
    "expertise" : "HTML5",
    "expertiseList" : ["Saas", "Angular", "Flash", "HTML5", "Nodejs"],
    "weight" : 200,
    "idUser" : "david-james",
    "photo" : "/images/people/perfil_2.png",
    "phone" : "+506-82221338",
    "email" : "david.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "David James",
    "expertise" : "Nodejs",
    "expertiseList" : ["Saas", "Angular", "Flash", "HTML5", "Nodejs"],
    "weight" : 100,
    "idUser" : "david-james",
    "photo" : "/images/people/perfil_2.png",
    "phone" : "+506-82221338",
    "email" : "david.qa+testing@whoknows.com",
    "occupation" : "UX Designer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Patricia Morgan",
    "expertise" : "Angular",
    "expertiseList" : ["Angular", "HTML5", "Nodejs", "Flash", "Saas"],
    "weight" : 500,
    "idUser" : "patricia-morgan",
    "photo" : "/images/people/perfil_3.png",
    "phone" : "+506-85239345",
    "email" : "patricia.qa+testing@whoknows.com",
    "occupation" : "Full Stack Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Patricia Morgan",
    "expertise" : "HTML5",
    "expertiseList" : ["Angular", "HTML5", "Nodejs", "Flash", "Saas"],
    "weight" : 400,
    "idUser" : "patricia-morgan",
    "photo" : "/images/people/perfil_3.png",
    "phone" : "+506-85239345",
    "email" : "patricia.qa+testing@whoknows.com",
    "occupation" : "Full Stack Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Patricia Morgan",
    "expertise" : "Nodejs",
    "expertiseList" : ["Angular", "HTML5", "Nodejs", "Flash", "Saas"],
    "weight" : 300,
    "idUser" : "patricia-morgan",
    "photo" : "/images/people/perfil_3.png",
    "phone" : "+506-85239345",
    "email" : "patricia.qa+testing@whoknows.com",
    "occupation" : "Full Stack Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Patricia Morgan",
    "expertise" : "Flash",
    "expertiseList" : ["Angular", "HTML5", "Nodejs", "Flash", "Saas"],
    "weight" : 200,
    "idUser" : "patricia-morgan",
    "photo" : "/images/people/perfil_3.png",
    "phone" : "+506-85239345",
    "email" : "patricia.qa+testing@whoknows.com",
    "occupation" : "Full Stack Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Patricia Morgan",
    "expertise" : "Saas",
    "expertiseList" : ["Angular", "HTML5", "Nodejs", "Flash", "Saas"],
    "weight" : 100,
    "idUser" : "patricia-morgan",
    "photo" : "/images/people/perfil_3.png",
    "phone" : "+506-85239345",
    "email" : "patricia.qa+testing@whoknows.com",
    "occupation" : "Full Stack Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Barbara Stuart",
    "expertise" : "Nodejs",
    "expertiseList" : ["Nodejs", "Flash", "Angular", "Saas", "HTML5"],
    "weight" : 500,
    "idUser" : "barbara-stuart",
    "photo" : "/images/people/perfil_4.png",
    "phone" : "+506-81302322",
    "email" : "barbara.qa+testing@whoknows.com",
    "occupation" : "Back-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Barbara Stuart",
    "expertise" : "Flash",
    "expertiseList" : ["Nodejs", "Flash", "Angular", "Saas", "HTML5"],
    "weight" : 400,
    "idUser" : "barbara-stuart",
    "photo" : "/images/people/perfil_4.png",
    "phone" : "+506-81302322",
    "email" : "barbara.qa+testing@whoknows.com",
    "occupation" : "Back-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Barbara Stuart",
    "expertise" : "Angular",
    "expertiseList" : ["Nodejs", "Flash", "Angular", "Saas", "HTML5"],
    "weight" : 300,
    "idUser" : "barbara-stuart",
    "photo" : "/images/people/perfil_4.png",
    "phone" : "+506-81302322",
    "email" : "barbara.qa+testing@whoknows.com",
    "occupation" : "Back-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Barbara Stuart",
    "expertise" : "Saas",
    "expertiseList" : ["Nodejs", "Flash", "Angular", "Saas", "HTML5"],
    "weight" : 200,
    "idUser" : "barbara-stuart",
    "photo" : "/images/people/perfil_4.png",
    "phone" : "+506-81302322",
    "email" : "barbara.qa+testing@whoknows.com",
    "occupation" : "Back-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Barbara Stuart",
    "expertise" : "HTML5",
    "expertiseList" : ["Nodejs", "Flash", "Angular", "Saas", "HTML5"],
    "weight" : 100,
    "idUser" : "barbara-stuart",
    "photo" : "/images/people/perfil_4.png",
    "phone" : "+506-81302322",
    "email" : "barbara.qa+testing@whoknows.com",
    "occupation" : "Back-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Margareth Smith",
    "expertise" : "Flash",
    "expertiseList" : ["Flash", "Saas", "HTML5", "Nodejs", "Angular"],
    "weight" : 500,
    "idUser" : "margareth-smith",
    "photo" : "/images/people/perfil_5.png",
    "phone" : "+506-82324322",
    "email" : "margareth.qa+testing@whoknows.com",
    "occupation" : "Front-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Margareth Smith",
    "expertise" : "Saas",
    "expertiseList" : ["Flash", "Saas", "HTML5", "Nodejs", "Angular"],
    "weight" : 400,
    "idUser" : "margareth-smith",
    "photo" : "/images/people/perfil_5.png",
    "phone" : "+506-82324322",
    "email" : "margareth.qa+testing@whoknows.com",
    "occupation" : "Front-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Margareth Smith",
    "expertise" : "HTML5",
    "expertiseList" : ["Flash", "Saas", "HTML5", "Nodejs", "Angular"],
    "weight" : 300,
    "idUser" : "margareth-smith",
    "photo" : "/images/people/perfil_5.png",
    "phone" : "+506-82324322",
    "email" : "margareth.qa+testing@whoknows.com",
    "occupation" : "Front-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Margareth Smith",
    "expertise" : "Nodejs",
    "expertiseList" : ["Flash", "Saas", "HTML5", "Nodejs", "Angular"],
    "weight" : 200,
    "idUser" : "margareth-smith",
    "photo" : "/images/people/perfil_5.png",
    "phone" : "+506-82324322",
    "email" : "margareth.qa+testing@whoknows.com",
    "occupation" : "Front-End Developer"
}'

curl -X POST 'http://localhost:9200/user/expertise' -d '{ 
    "name" : "Margareth Smith",
    "expertise" : "Angular",
    "expertiseList" : ["Flash", "Saas", "HTML5", "Nodejs", "Angular"],
    "weight" : 100,
    "idUser" : "margareth-smith",
    "photo" : "/images/people/perfil_5.png",
    "phone" : "+506-82324322",
    "email" : "margareth.qa+testing@whoknows.com",
    "occupation" : "Front-End Developer"
}'